#!/bin/bash --

function custom_vcs() {
    export POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
#    export POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=' '
    prompt_vcs $1 $2
#    export POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=''
    export POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
}

() {
    _bashrc_my_ssh=''
    [[ -n "$SSH_CLIENT$SSH_CONNECTION$SSH_TTY" ]] && {
        _bashrc_my_ssh=${HOST:0:4}
        [[ ${#HOST} -gt 4 ]] && _bashrc_my_ssh=$_bashrc_my_ssh$HOST[${#HOST}]
    }
    _bashrc_my_colog_bg=0

    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( time custom_user dir custom_vcs status )
    export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( background_jobs )
    export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS
    export POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
    export POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
    export POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=''
    export POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=' '
    export POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
    export POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
    export POWERLEVEL9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS=''
    export POWERLEVEL9K_RIGHT_SEGMENT_END_SEPARATOR=''

    # time
    export POWERLEVEL9K_TIME_BACKGROUND=$_bashrc_my_colog_bg
    export POWERLEVEL9K_TIME_FOREGROUND=${_bashrc_my_ssh:+1}3
    # custom_user
    export DEFAULT_USER=$USER
    export POWERLEVEL9K_CUSTOM_USER='echo '${_bashrc_my_ssh:+$_bashrc_my_ssh:}'$USER'
    export POWERLEVEL9K_CUSTOM_USER_BACKGROUND=$_bashrc_my_colog_bg
    export POWERLEVEL9K_CUSTOM_USER_FOREGROUND=12
    # dir
    #export POWERLEVEL9K_HOME_FOLDER_ABBREVIATION='⌂'
    export POWERLEVEL9K_SHORTEN_STRATEGY=Default
    export POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
    export POWERLEVEL9K_DIR_SHOW_WRITABLE=true
    export POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=$_bashrc_my_colog_bg
    export POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=7
    export POWERLEVEL9K_DIR_HOME_BACKGROUND=$_bashrc_my_colog_bg
    export POWERLEVEL9K_DIR_HOME_FOREGROUND=$POWERLEVEL9K_DIR_DEFAULT_FOREGROUND
    export POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=$_bashrc_my_colog_bg
    export POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=$POWERLEVEL9K_DIR_DEFAULT_FOREGROUND
    export POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND=$_bashrc_my_colog_bg
    export POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND=7
    export POWERLEVEL9K_DIR_ETC_BACKGROUND=$POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND
    export POWERLEVEL9K_DIR_ETC_FOREGROUND=$POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND
    # custom_vcs
    export POWERLEVEL9K_CUSTOM_VCS='custom_vcs $1 $2'
    export POWERLEVEL9K_CUSTOM_VCS_BACKGROUND=$_bashrc_my_colog_bg
    export POWERLEVEL9K_VCS_CLEAN_FOREGROUND=2
    export POWERLEVEL9K_VCS_CLEAN_BACKGROUND=$_bashrc_my_colog_bg
    export POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=6
    export POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=$_bashrc_my_colog_bg
    export POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=3
    export POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=$_bashrc_my_colog_bg
    # status
    export POWERLEVEL9K_STATUS_CROSS=true
    export POWERLEVEL9K_STATUS_OK_BACKGROUND=$_bashrc_my_colog_bg
    export POWERLEVEL9K_STATUS_ERROR_BACKGROUND=$_bashrc_my_colog_bg
    # background_jobs
    export POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=$_bashrc_my_colog_bg
    export POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=14

    unset _bashrc_my_colog_bg _bashrc_my_ssh
}
